### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by palashd1** [etomica/mapped-averaging#1]
Dear Professor,

While using pyHMA package I got encountered with the following error 

`Traceback (most recent call last):
  File "/home/palash/anaconda3/envs/my_env/bin/pyhma", line 54, in <module>
    proc.process(verbose=verbose, steps_tot=steps_tot)
  File "/home/palash/anaconda3/envs/my_env/lib/python3.8/site-packages/pyhma/processor.py", line 126, in process
    pressure_lat = self.pressure[0] - self.pressure_ig
IndexError: list index out of range
`
I have used the following command 

`pyhma --pressure_qh=4.95 --steps_eq=1000 --steps_tot=5000 --blocksize=90  --meV  -v -r {vasprun-1.xml,vasprun-2.xml}`

I have changed the outputs with different cell size and AIMD simulation steps, but the error is same throughout.
Please guide me.

Thank you.

Regards,
Palash Swarnakar

**Comment by ajschult** [comment]
Do your vasprun xml files contain sections like

  <varray name="stress" >
?

This is where the self.pressure values should come from.

**Comment by palashd1** [comment]
Professor,

only this line
`<?xml version="1.0" encoding="ISO-8859-1"?>`

Thank you.

**Comment by palashd1** [comment]
Professor,

only this line
`<?xml version="1.0" encoding="ISO-8859-1"?>`

Thank you.

**Comment by palashd1** [comment]
Professor,

only this line
`<?xml version="1.0" encoding="ISO-8859-1"?>`

Thank you.

**Comment by ajschult** [comment]
What do you have ISIF set to?

https://www.vasp.at/wiki/index.php/ISIF

**Comment by palashd1** [comment]
Dear Professor,

Thank you for getting back to me so quickly.
Initially, I took the default ISIF; now, I have formatted it according to the input file. I got the output without errors.
Please accept my sincere thanks once again, Professor.

Regards,
Palash Swarnakar

**Comment by palashd1** [comment]
Dear Professor,

Thank you for getting back to me so quickly.
Initially, I took the default ISIF; now, I have formatted it according to the input file. I got the output without errors.
Please accept my sincere thanks once again, Professor.

Regards,
Palash Swarnakar
